metadata:
- appName: ''
  dataId: db-common.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: tlmall-order.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: nacos-discovery.yml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: tlmall-storage.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: tlmall-account.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: seata-client.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: sentinel-dashboard.yml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: tlmall-gateway.yml
  group: DEFAULT_GROUP
  type: yaml
